url: https://sitedesk.github.io

# Site settings
title: Sitedesk
email: your-email@domain.com
description: "Sitedesk is a BIM software tool helping you connect and manage your traditional construction project and BIM project data and documents"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: a2c037
  secondary: dc911b
  dark: 3f3e3e
  secondary-dark: 3f3e3e
  dark-lighter: 868686

# Team names, titles and social links
people:
  - name: Carl Green
    pic: 1
    position: Head of Engineering Services, Wyre Council
    quote: “We were initially worried about how to make best use of the data with all of the different tools that were being used on the programme. It quickly became apparent that we needed to identify a simple-to-use tool that enables us to use and capture information throughout the construction and operational processes that ideally can be used in the field. We managed to find a tool called Sitedesk …”
  - name: Peter Trebilcock
    pic: 2
    position: Design & BIM Programme Director, Balfour Beatty Construction Services UK
    quote: “The use of field devices is playing a significant role in delivering better management of data and increased business efficiency across our business. We are currently deploying them across a portfolio of education and commercial projects”

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty