name: Sitedesk
url: https://sitedesk.com
excerpt_separator: <!--more-->
paginate: 5
paginate_path: "news/page:num"
gems:
 - jekyll-paginate
 - jekyll-sitemap
 - jekyll-redirect-from
permalink: pretty
collections:
  case-studies:
    output: true
  events:
    output: true
